# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb_RFW.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpb_RFW.proto\"\xa0\x01\n\x03Rfw\x12\n\n\x02ID\x18\x01 \x01(\t\x12\x15\n\rBenchmarkType\x18\x02 \x01(\t\x12\x16\n\x0eWorkloadMetric\x18\x03 \x01(\t\x12\x11\n\tBatchUnit\x18\x04 \x01(\t\x12\x0f\n\x07\x42\x61tchID\x18\x05 \x01(\t\x12\x11\n\tBatchSize\x18\x06 \x01(\t\x12\x10\n\x08\x44\x61taType\x18\x07 \x01(\t\x12\x15\n\rDataAnalytics\x18\x08 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pb_RFW_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RFW._serialized_start=17
  _RFW._serialized_end=177
# @@protoc_insertion_point(module_scope)
