# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RFD.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tRFD.proto\"U\n\x03Rfd\x12\n\n\x02ID\x18\x01 \x01(\t\x12\x13\n\x0bLastBatchID\x18\x02 \x01(\t\x12\x17\n\x0b\x44\x61taSamples\x18\x03 \x03(\x01\x42\x02\x10\x01\x12\x14\n\x0c\x44\x61taAnalytic\x18\x04 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RFD_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RFD.fields_by_name['DataSamples']._options = None
  _RFD.fields_by_name['DataSamples']._serialized_options = b'\020\001'
  _RFD._serialized_start=13
  _RFD._serialized_end=98
# @@protoc_insertion_point(module_scope)
